# Generated by Django 3.1 on 2020-09-05 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20200906_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 1 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
