# Generated by Django 3.1 on 2020-09-08 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_auto_20200906_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
