# Generated by Django 3.1 on 2020-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_auto_20200908_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='joined_from',
            field=models.DateField(auto_now=True),
        ),
    ]
