# Generated by Django 3.1 on 2020-09-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20200917_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='joined_from',
            field=models.DateField(),
        ),
    ]
