# Generated by Django 3.1 on 2020-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_auto_20200917_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=15, null=True),
        ),
    ]
