# Generated by Django 3.1 on 2020-09-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0016_auto_20200917_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
