# Generated by Django 3.1 on 2020-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_auto_20200918_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edited_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
