# Generated by Django 3.1 on 2020-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0025_auto_20200923_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='joined_from',
            field=models.DateField(auto_now_add=True),
        ),
    ]
