# Generated by Django 3.1 on 2020-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_auto_20200924_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=50),
        ),
    ]
