# Generated by Django 3.1 on 2020-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0031_auto_20200925_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
