# Generated by Django 3.1 on 2020-10-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0033_auto_20201005_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='joined_from',
            field=models.DateField(auto_now_add=True),
        ),
    ]
