# Generated by Django 3.1 on 2020-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0034_auto_20201005_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='joined_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
