# Generated by Django 3.1 on 2020-10-05 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0035_auto_20201005_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=755)),
            ],
        ),
    ]
