# Generated by Django 3.1 on 2020-10-05 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0037_auto_20201005_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')]),
        ),
    ]
