# Generated by Django 3.1 on 2020-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0039_auto_20201005_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
