# Generated by Django 3.1 on 2020-10-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0041_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
