# Generated by Django 3.1 on 2020-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0043_auto_20201005_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
